const TRAILS = [
  {id:1,name:"Mardi Himal Trek",district:"Kaski",province:"Gandaki",difficulty:"Moderate",days:7,distance:"41 km",altitude:"4,500 m",cost:28000,rating:4.9,reviews:128,type:"Mountain",start:"Kande",end:"Siding",lat:28.331,lng:83.809,image:"https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",tags:["nature","adventure","photography"],desc:"A compact Himalayan adventure with dramatic views of Machhapuchhre and Annapurna."},
  {id:2,name:"Poon Hill Ghorepani",district:"Myagdi / Kaski",province:"Gandaki",difficulty:"Easy",days:4,distance:"32 km",altitude:"3,210 m",cost:15000,rating:4.8,reviews:214,type:"Mountain",start:"Nayapul",end:"Ghorepani",lat:28.402,lng:83.724,image:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",tags:["nature","comfort","photography"],desc:"A friendly classic for sunrise seekers, mountain views, rhododendron forests and teahouse comfort."},
  {id:3,name:"Langtang Valley Trek",district:"Rasuwa",province:"Bagmati",difficulty:"Moderate",days:8,distance:"77 km",altitude:"3,870 m",cost:30000,rating:4.8,reviews:176,type:"Valley",start:"Syabrubesi",end:"Kyanjin Gompa",lat:28.213,lng:85.534,image:"https://images.unsplash.com/photo-1521292270410-a8c4d716d518?auto=format&fit=crop&w=1200&q=80",tags:["adventure","cultural","nature"],desc:"A beautiful valley route combining forests, high peaks, villages and Tibetan-influenced culture."},
  {id:4,name:"Gosaikunda Lake",district:"Rasuwa",province:"Bagmati",difficulty:"Challenging",days:6,distance:"46 km",altitude:"4,380 m",cost:22000,rating:4.7,reviews:142,type:"Lake",start:"Dhunche",end:"Gosaikunda",lat:28.085,lng:85.414,image:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80",tags:["spiritual","adventure","nature"],desc:"A high-altitude pilgrimage landscape of alpine lakes, ridges and sweeping Himalayan scenery."},
  {id:5,name:"Everest Base Camp",district:"Solukhumbu",province:"Koshi",difficulty:"Challenging",days:14,distance:"130 km",altitude:"5,364 m",cost:85000,rating:4.9,reviews:392,type:"Mountain",start:"Lukla",end:"EBC",lat:27.988,lng:86.925,image:"https://images.unsplash.com/photo-1529921879218-f99546d03a88?auto=format&fit=crop&w=1200&q=80",tags:["adventure","cultural","spiritual"],desc:"Nepal's iconic high-altitude journey through Sherpa settlements toward the world's highest mountain."},
  {id:6,name:"Khopra Danda Trek",district:"Myagdi",province:"Gandaki",difficulty:"Moderate",days:8,distance:"56 km",altitude:"3,660 m",cost:32000,rating:4.8,reviews:88,type:"Ridge",start:"Ghandruk",end:"Khopra",lat:28.443,lng:83.714,image:"https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80",tags:["nature","adventure","photography"],desc:"A quieter alternative with ridge-top panoramas, forests and a peaceful community trekking feel."},
  {id:7,name:"Tamang Heritage Trail",district:"Rasuwa",province:"Bagmati",difficulty:"Easy",days:6,distance:"55 km",altitude:"3,165 m",cost:24000,rating:4.6,reviews:64,type:"Cultural",start:"Syabrubesi",end:"Briddim",lat:28.184,lng:85.338,image:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80",tags:["cultural","comfort","nature"],desc:"Village homestays, Tamang heritage, warm hospitality and mountain scenery in one relaxed route."},
  {id:8,name:"Panch Pokhari Trek",district:"Sindhupalchok",province:"Bagmati",difficulty:"Challenging",days:9,distance:"64 km",altitude:"4,100 m",cost:29000,rating:4.7,reviews:51,type:"Lake",start:"Bhotang",end:"Panch Pokhari",lat:28.016,lng:85.79,image:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",tags:["spiritual","adventure","nature"],desc:"Five sacred alpine lakes, dramatic ridges and a less-crowded Himalayan experience."},
  {id:9,name:"Kakani Shivapuri Day Hike",district:"Kathmandu / Nuwakot",province:"Bagmati",difficulty:"Easy",days:1,distance:"12 km",altitude:"2,732 m",cost:2500,rating:4.5,reviews:119,type:"Forest",start:"Kakani",end:"Shivapuri",lat:27.815,lng:85.273,image:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",tags:["nature","comfort","photography"],desc:"A practical day escape near Kathmandu for fresh air, forest trails and mountain viewpoints."},
  {id:10,name:"Tilicho Lake",district:"Manang",province:"Gandaki",difficulty:"Challenging",days:10,distance:"82 km",altitude:"4,919 m",cost:42000,rating:4.9,reviews:73,type:"Lake",start:"Besisahar",end:"Tilicho",lat:28.697,lng:84.021,image:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",tags:["adventure","nature","photography"],desc:"A demanding high-altitude journey to one of the world's highest lakes."}
];

// Added more hike / day-hike options
TRAILS.push(
  {id:11,name:"Nagarkot Sunrise Hike",district:"Bhaktapur",province:"Bagmati",difficulty:"Easy",days:1,distance:"8 km",altitude:"2,175 m",cost:2000,rating:4.6,reviews:210,type:"Day Hike",start:"Nagarkot",end:"Nagarkot",lat:27.704,lng:85.453,image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",tags:["sunrise","views","photography"],desc:"Short hike to a classic viewpoint above the Kathmandu Valley for sunrise over the Himalayas."},
  {id:12,name:"Chandragiri Hill Hike",district:"Kathmandu",province:"Bagmati",difficulty:"Easy",days:1,distance:"6 km",altitude:"2,551 m",cost:1500,rating:4.5,reviews:142,type:"Day Hike",start:"Thankot",end:"Chandragiri",lat:27.646,lng:85.217,image:"https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",tags:["views","forest","family"],desc:"A pleasant uphill forest trail with panoramic views of the Himalayas and the Kathmandu valley."},
  {id:13,name:"Dhampus Village Hike",district:"Kaski",province:"Gandaki",difficulty:"Easy",days:1,distance:"11 km",altitude:"1,650 m",cost:1800,rating:4.7,reviews:98,type:"Village Hike",start:"Phedi",end:"Dhampus",lat:28.292,lng:83.955,image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",tags:["culture","views","short"],desc:"A cultural day-hike from Pokhara to Dhampus village with mountain panoramas and Gurung hospitality."},
  {id:14,name:"Sarangkot Sunrise Hike",district:"Kaski",province:"Gandaki",difficulty:"Easy",days:1,distance:"5 km",altitude:"1,592 m",cost:1500,rating:4.6,reviews:184,type:"Day Hike",start:"Pokhara",end:"Sarangkot",lat:28.214,lng:83.991,image:"https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80",tags:["sunrise","short","views"],desc:"Popular sunrise viewpoint above Pokhara reachable via a short, rewarding hike."},
  {id:15,name:"Bandipur Cultural Hike",district:"Tanahun",province:"Gandaki",difficulty:"Moderate",days:2,distance:"18 km",altitude:"1,030 m",cost:4500,rating:4.5,reviews:67,type:"Cultural Hike",start:"Damauli",end:"Bandipur",lat:27.866,lng:84.043,image:"https://images.unsplash.com/photo-1495567720989-cebdbdd97913?auto=format&fit=crop&w=1200&q=80",tags:["culture","heritage","nature"],desc:"A two-day route visiting the preserved hill-town of Bandipur, villages and viewpoints over the Himalayas."},
  {id:16,name:"Nuwakot Fort Hike",district:"Nuwakot",province:"Bagmati",difficulty:"Easy",days:1,distance:"10 km",altitude:"1,200 m",cost:2000,rating:4.4,reviews:45,type:"Historic Hike",start:"Nuwakot Bazaar",end:"Nuwakot Fort",lat:27.922,lng:85.136,image:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",tags:["history","views","day"],desc:"A gentle hike up to the historic Nuwakot Durbar and fort with valley views and cultural points of interest."}
);

const USERS = [
  {id:101,name:"Sujal Gurung",initials:"SG",location:"Pokhara, Gandaki",experience:"Intermediate",languages:["Nepali","English"],interests:["nature","adventure"],bio:"Weekend hiker who loves sunrise trails and quiet teahouses.",match:96},
  {id:102,name:"Riya Lama",initials:"RL",location:"Kathmandu, Bagmati",experience:"Beginner",languages:["Nepali","English","Tamang"],interests:["cultural","nature"],bio:"Looking for friendly groups and beginner-friendly trails.",match:92},
  {id:103,name:"Aayush Karki",initials:"AK",location:"Lalitpur, Bagmati",experience:"Advanced",languages:["Nepali","English","Hindi"],interests:["adventure","photography"],bio:"Mountain photography, long weekends and high passes.",match:89},
  {id:104,name:"Nima Sherpa",initials:"NS",location:"Solukhumbu, Koshi",experience:"Expert",languages:["Sherpa","Nepali","English"],interests:["adventure","spiritual"],bio:"High-altitude trekker and local route enthusiast.",match:87},
  {id:105,name:"Prakriti Rai",initials:"PR",location:"Ilam, Koshi",experience:"Intermediate",languages:["Nepali","English","Maithili"],interests:["nature","cultural"],bio:"I hike for landscapes, stories and good conversations.",match:85},
  {id:106,name:"Bibek Thapa",initials:"BT",location:"Bhaktapur, Bagmati",experience:"Intermediate",languages:["Nepali","English"],interests:["comfort","nature"],bio:"Tea-house fan. Planning short treks around Nepal.",match:82}
];

const GROUPS = [
  {id:1,name:"Mardi Weekend Crew",trail:"Mardi Himal Trek",date:"Sep 12–18, 2026",members:7,max:10,level:"Intermediate",owner:"Sujal Gurung",desc:"Sunrise, photography and a relaxed pace.",avatar:"MC"},
  {id:2,name:"EBC Dream Team",trail:"Everest Base Camp",date:"Oct 3–17, 2026",members:5,max:8,level:"Advanced",owner:"Nima Sherpa",desc:"Preparing together, sharing logistics and keeping the group small.",avatar:"ED"},
  {id:3,name:"Langtang First Timers",trail:"Langtang Valley Trek",date:"Sep 25–Oct 2, 2026",members:6,max:10,level:"Beginner",owner:"Riya Lama",desc:"A supportive group for first multi-day trekking experience.",avatar:"LF"},
  {id:4,name:"Lake Seekers Nepal",trail:"Gosaikunda Lake",date:"Oct 10–15, 2026",members:4,max:8,level:"Intermediate",owner:"Prakriti Rai",desc:"Nature and spirituality with a moderate pace.",avatar:"LS"}
];

const PROVINCES = ["All","Koshi","Madhesh","Bagmati","Gandaki","Lumbini","Karnali","Sudurpashchim"];
